spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sample_schema
    driver-class-name: org.postgresql.Driver
    username: sample_schema
    password: password
